# Generated by Django 5.0.4 on 2024-05-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CsvTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("csv_file", models.FileField(upload_to="static/demo/csv_task/")),
                ("excel_file", models.FileField(upload_to="static/demo/csv_task/")),
                ("updated_excel_file", models.FileField(blank=True, null=True, upload_to="static/demo/csv_task/")),
                ("csv_file_uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("excel_file_uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("python_script_success", models.BooleanField(default=False)),
            ],
        ),
    ]
