exclude: ^static/.*|assets/.*|/migrations/.*|\.min\.js$|\.min\.css$|\.css\.map$|\.min\.js$|\.js\.map$|\.svg$|\.gb/.*
default_stages: [pre-commit]
default_language_version:
   python: python3.11

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.11
    hooks:
      - id: ruff
        exclude: >
          (?x)(
            .*\/templates\/.*|
            .*cookiecutter.*|
            \.gb/.*|
            .*/site-packages/.*
          )
      - id: ruff-format
        exclude: >
          (?x)(
            .*\/templates\/.*|
            .*cookiecutter.*|
            \.gb/.*|
            .*/site-packages/.*
          )
