# syntax = docker/dockerfile:1.5
FROM python:3.11-bookworm
ENV PYTHONUNBUFFERED=1

# install node/npm
RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
    --mount=target=/var/cache/apt,type=cache,sharing=locked \
    rm -f /etc/apt/apt.conf.d/docker-clean && \
    echo "deb https://deb.nodesource.com/node_20.x bookworm main" > /etc/apt/sources.list.d/nodesource.list && \
    wget -qO- https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - && \
    apt-get update && \
    apt-get install -yqq nodejs \
    # install gettext for translations
    gettext \
    # required on M2 / ARM architecture
    libpq-dev

# create code directory
RUN mkdir /code
WORKDIR /code

# install uv
COPY --from=ghcr.io/astral-sh/uv:0.5.2 /uv /uvx /bin/

# install python requirements
# copy just dependency file(s) and install before rest of code to avoid having to
# reinstall packages during build every time code changes

# remove the following lines as they seem be causing issues
# COPY requirements.txt requirements.txt
# COPY dev-requirements.txt dev-requirements.txt
# COPY requirements requirements/

# Copy requirements files
COPY requirements/requirements.txt requirements/requirements.txt
COPY requirements/dev-requirements.txt requirements/dev-requirements.txt
COPY requirements/prod-requirements.txt requirements/prod-requirements.txt

# Install dependencies
RUN pip install -r requirements/requirements.txt
RUN pip install -r requirements/dev-requirements.txt
RUN pip install -r requirements/prod-requirements.txt



# Install dependencies using uv
RUN --mount=type=cache,target=/root/.cache \
    uv pip install --system -r requirements/requirements.txt \
    -r requirements/dev-requirements.txt \
    -r requirements/prod-requirements.txt

# copy code files
COPY . /code/
