services:
  db:
    image: postgres
    # persist data beyond lifetime of container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=general_balance
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 2s
      retries: 10
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    # persistent storage
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: '1'
      PYTHONDONTWRITEBYTECODE: '1'
      DATABASE_HOST: 'db'           # Add these
      DATABASE_NAME: 'general_balance'
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: 'postgres'
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  celery:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A general_balance worker -l INFO --beat --pool=solo
    volumes:
      - .:/code
    environment:
      PYTHONUNBUFFERED: '1'
      PYTHONDONTWRITEBYTECODE: '1'
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
