default_context:
  _pegasus_version: 2024.2.4
  author_name: Kyle
  ci: github_actions
  css_framework: bootstrap
  css_theme: default
  database: postgres
  deploy_platform: none
  description: excel automation made simple
  docker_setup: default
  domain_name: generalbalance.com
  email: kylehunt22@gmail.com
  enable_github_login: n
  enable_google_login: n
  enable_twitter_login: n
  front_end_framework: react
  include_static_files: y
  marketing_email_platform: none
  post_process: y
  project_name: General Balance
  project_slug: general_balance
  stripe_payment_mode: checkout
  subscription_billing_model: default
  subscription_pricing_ui: in_app
  use_2fa: y
  use_admin_docs: n
  use_api_keys: y
  use_async_example: y
  use_cloud_media_storage: y
  use_debug_toolbar: n
  use_docker: n
  use_ecommerce_example: n
  use_examples: y
  use_impersonation: y
  use_openai: y
  use_sentry: n
  use_subscriptions: n
  use_teams: y
  use_teams_example: y
  use_translations: y
  use_wagtail: y
