services:
  - type: web
    name: general_balance
    env: python
    buildCommand: "./deploy/build.sh"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 0 general_balance.wsgi:application"
    region: oregon
    plan: free
    numInstances: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.3
      - key: NODE_VERSION
        value: 20.10.0
      - key: DEBUG
        value: false
      - key: DJANGO_SETTINGS_MODULE
        value: general_balance.settings_production
      - key: DJANGO_DATABASE_NAME
        fromDatabase:
          name: general_balance
          property: database
      - key: DJANGO_DATABASE_USER
        fromDatabase:
          name: general_balance
          property: user
      - key: DJANGO_DATABASE_PASSWORD
        fromDatabase:
          name: general_balance
          property: password
      - key: DJANGO_DATABASE_HOST
        fromDatabase:
          name: general_balance
          property: host
      - key: DJANGO_DATABASE_PORT
        fromDatabase:
          name: general_balance
          property: port
      - key: REDIS_HOST
        fromService:
          type: redis
          name: general_balance-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: general_balance-redis
          property: port
      - key: SECRET_KEY
        sync: false
      - key: GOOGLE_ANALYTICS_ID
        sync: false
      # KH added
      


# Celery task worker (not available on 'free' plan)
#  - type: worker
#    name: general_balance_celery
#    env: python
#    buildCommand: "./deploy/build_celery.sh"
#    startCommand: celery -A general_balance worker -l INFO --beat --concurrency 2
#    region: oregon
#    plan: starter
#    numInstances: 1
#    envVars:
#      - key: PYTHON_VERSION
#        value: 3.11.3
#      - key: NODE_VERSION
#        value: 20.10.0
#      - key: DEBUG
#        value: false
#      - key: DJANGO_SETTINGS_MODULE
#        value: general_balance.settings_production
#      - key: DJANGO_DATABASE_NAME
#        fromDatabase:
#          name: general_balance
#          property: database
#      - key: DJANGO_DATABASE_USER
#        fromDatabase:
#          name: general_balance
#          property: user
#      - key: DJANGO_DATABASE_PASSWORD
#        fromDatabase:
#          name: general_balance
#          property: password
#      - key: DJANGO_DATABASE_HOST
#        fromDatabase:
#          name: general_balance
#          property: host
#      - key: DJANGO_DATABASE_PORT
#        fromDatabase:
#          name: general_balance
#          property: port
#      - key: REDIS_HOST
#        fromService:
#          type: redis
#          name: general_balance-redis
#          property: host
#      - key: REDIS_PORT
#        fromService:
#          type: redis
#          name: general_balance-redis
#          property: port
#      - key: SECRET_KEY
#        sync: false
#      - key: GOOGLE_ANALYTICS_ID
#        sync: false

# Redis instance (for celery and caching)
  - type: redis
    name: general_balance-redis
    ipAllowList: []
    plan: free

# Postgres database
databases:
  - name: general_balance
    plan: free
    databaseName: general_balance
    user: general_balance
    ipAllowList: [] # only allow internal connections
