# Generated by Django 5.0.6 on 2024-06-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_company_customuser_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="company",
        ),
        migrations.DeleteModel(
            name="Company",
        ),
    ]
