# Generated by Django 5.0.4 on 2024-05-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amwell", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankrec",
            name="csv_file",
            field=models.FileField(upload_to="static/bank_rec/"),
        ),
        migrations.AlterField(
            model_name="bankrec",
            name="excel_file",
            field=models.FileField(upload_to="static/bank_rec/"),
        ),
        migrations.AlterField(
            model_name="bankrec",
            name="updated_excel_file",
            field=models.FileField(blank=True, null=True, upload_to="static/bank_rec/"),
        ),
    ]
