# Generated by Django 5.0.4 on 2024-05-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amwell", "0002_alter_bankrec_csv_file_alter_bankrec_excel_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankrec",
            name="updated_excel_file",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
