# Generated by Django 5.0.4 on 2024-05-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amwell", "0003_alter_bankrec_updated_excel_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankrec",
            name="updated_excel_file",
            field=models.FileField(blank=True, null=True, upload_to="static/bank_rec/"),
        ),
    ]
