# Generated by Django 5.1.3 on 2024-12-07 15:31

import apps.workflows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('template_file', models.FileField(help_text='Excel template file that will be used', upload_to=apps.workflows.models.workflow_directory_path)),
                ('script_file', models.FileField(help_text='Python script that processes the data', upload_to=apps.workflows.models.workflow_directory_path)),
                ('data_source', models.CharField(choices=[('CSV', 'CSV File'), ('EXCEL', 'Excel File'), ('NETSUITE', 'NetSuite API')], default='EXCEL', max_length=10)),
                ('data_file', models.FileField(blank=True, help_text='Data file (CSV or Excel) if applicable', null=True, upload_to=apps.workflows.models.workflow_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='excel_data_workflow',
        ),
    ]
