# Generated by Django 5.1.3 on 2024-12-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_workflow_delete_excel_data_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='data_source',
            field=models.CharField(choices=[('csv', 'CSV File'), ('excel', 'Excel File'), ('netsuite', 'NetSuite API'), ('salesforce', 'Salesforce API')], default='csv', help_text='Select the type of data source for this workflow', max_length=20),
        ),
    ]
