# Generated by Django 5.1.3 on 2024-12-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_alter_workflow_data_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='slug',
        ),
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='script_file',
            field=models.FileField(null=True, upload_to='workflows/scripts/'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='template_file',
            field=models.FileField(null=True, upload_to='workflows/templates/'),
        ),
    ]
