# Generated by Django 5.1.3 on 2025-01-09 13:49

import apps.workflows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_remove_workflow_slug_alter_workflow_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='script_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.workflows.models.workflow_directory_path),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='template_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.workflows.models.workflow_directory_path),
        ),
    ]
