# Generated by Django 5.1.3 on 2025-02-16 02:42

import apps.workflows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_alter_workflow_script_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.workflows.models.workflow_directory_path),
        ),
    ]
