# Generated by Django 5.1.3 on 2025-02-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_alter_workflow_data_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
