# Generated by Django 5.1.3 on 2025-02-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_alter_workflow_description_alter_workflow_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='latest_output_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
